// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_bRYZzGAq6vpkkvzjEGPxAzCDUW9FMno',
    appId: '1:352090353287:web:your-web-app-id',
    messagingSenderId: '352090353287',
    projectId: 'plant-disease-detector-870c9',
    authDomain: 'plant-disease-detector-870c9.firebaseapp.com',
    storageBucket: 'plant-disease-detector-870c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_bRYZzGAq6vpkkvzjEGPxAzCDUW9FMno',
    appId: '1:352090353287:android:7fd38120eda2e958351222',
    messagingSenderId: '352090353287',
    projectId: 'plant-disease-detector-870c9',
    storageBucket: 'plant-disease-detector-870c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_bRYZzGAq6vpkkvzjEGPxAzCDUW9FMno',
    appId: '1:352090353287:ios:your-ios-app-id',
    messagingSenderId: '352090353287',
    projectId: 'plant-disease-detector-870c9',
    storageBucket: 'plant-disease-detector-870c9.firebasestorage.app',
    iosBundleId: 'com.example.plantDiseaseDetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_bRYZzGAq6vpkkvzjEGPxAzCDUW9FMno',
    appId: '1:352090353287:ios:your-macos-app-id',
    messagingSenderId: '352090353287',
    projectId: 'plant-disease-detector-870c9',
    storageBucket: 'plant-disease-detector-870c9.firebasestorage.app',
    iosBundleId: 'com.example.plantDiseaseDetector',
  );
}
