import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

// Your own imports
import 'firebase_options.dart'; // <-- Make sure this file exists (generated by FlutterFire)
import 'providers/auth_provider.dart';
import 'screens/auth/login_screen.dart';
import 'screens/auth/register_screen.dart';
import 'screens/splash_screen.dart';
import 'screens/main_navigation.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // ✅ Initialize Firebase safely
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const ProviderScope(child: PlantDiseaseApp()));
}

class PlantDiseaseApp extends ConsumerWidget {
  const PlantDiseaseApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStateProvider);

    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Plant Disease Detector',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: const Color(0xFF2E7D32)),
        useMaterial3: true,
      ),
      home: authState.when(
        loading: () {
          debugPrint('⏳ Loading Firebase Auth State...');
          return const SplashScreen();
        },
        error: (error, stack) {
          debugPrint('❌ Auth Error: $error');
          return const LoginScreen();
        },
        data: (user) {
          if (user == null) {
            debugPrint('👤 No user logged in → Showing LoginScreen');
            return const LoginScreen();
          } else {
            debugPrint('✅ Logged in as ${user.email}');
            return const MainNavigation();
          }
        },
      ),
      routes: {
        '/login': (_) => const LoginScreen(),
        '/register': (_) => const RegisterScreen(),
        '/home': (_) => const MainNavigation(),
      },
    );
  }
}
